version: "3.7"

volumes:
  oncologic_db_data: {}
  minio_data: {}

services:
  # Oncologic DB
  oncologic_db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - oncologic_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"

  # Oncologic Service
  oncologic_service:
    image: hasura/graphql-engine:v1.3.0.cli-migrations-v2
    ports:
      - "8080:8080"
    depends_on:
      - "oncologic_db"
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:$POSTGRES_PASSWORD@oncologic_db:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
    links:
      - oncologic_db

  # Minio
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: "${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}"
    entrypoint: sh
    command: "-c 'mkdir -p /export/oncologic && /usr/bin/minio server /export'"
    volumes:
      - "minio_data:/data"

  # HBP
  hasura_backend_plus:
    image: nhost/hasura-backend-plus:v2.1.0
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: "http://oncologic_service:8080/v1/graphql"
      HASURA_GRAPHQL_ADMIN_SECRET: "$HASURA_GRAPHQL_ADMIN_SECRET"
      JWT_ALGORITHM: RS512
      AUTO_MIGRATE: "false"
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: oncologic
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}"
      MIN_PASSWORD_LENGTH: 6
    links:
      - oncologic_service
      - minio
    depends_on:
      - oncologic_service
      - minio
    ports:
      - "8000:3000"
    volumes:
      - ./storage-rules:/app/custom/storage-rules
